# Generated by Django 3.2.5 on 2021-07-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_deacth',
            new_name='date_of_death',
        ),
    ]
